version: '3.4'
services:
#  Optional
#  img-recognition-share:
#    image: ${docker.share.image}:${alfresco.share.version}
#    environment:
#      REPO_HOST: img-recognition-acs
#      REPO_PORT: 8080
#    ports:
#      - "${share.port}:8080"
  img-recognition-acs:
    image: alfresco-content-services-img-recognition:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../target
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
    ports:
      - "${acs.port}:8080"
      - "${acs.debug.port}:8888"
    volumes:
      - img-recognition-acs-volume:/usr/local/tomcat/alf_data
    depends_on:
      - img-recognition-postgres
  img-recognition-share:
    image: alfresco/alfresco-share:${alfresco.share.version}
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
      REPO_HOST: img-recognition-acs
      REPO_PORT: 8080
    ports:
      - "${share.port}:8080"
      - "${share.debug.port}:8888"
  img-recognition-postgres:
    image: postgres:11.6
    environment:
      POSTGRES_DB: alfresco
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - "${postgres.port}:5432"
    volumes:
      - img-recognition-db-volume:/var/lib/postgresql/data
  img-recognition-ass:
    image: alfresco/alfresco-search-services:1.4.0
    environment:
      SOLR_ALFRESCO_HOST: img-recognition-acs
      SOLR_ALFRESCO_PORT: 8080
      SOLR_SOLR_HOST: img-recognition-ass
      SOLR_SOLR_PORT: 8983
      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
      ALFRESCO_SECURE_COMMS: none
    ports:
      - "8983:8983"
    volumes:
      - img-recognition-ass-volume:/opt/alfresco-search-services/contentstore
      - img-recognition-ass-volume:/opt/alfresco-search-services/data
volumes:
  img-recognition-acs-volume:
    external: true
  img-recognition-db-volume:
    external: true
  img-recognition-ass-volume:
    external: true